# Практическая работа №4

Выполнил студент гр. 9372 Чернышев Андрей

## Цель работы
Освоение основных понятий, связанных с корреляционной зависимостью
между случайными величинами, статистическими гипотезами и проверкой их «справедливости».

## Основные теоретические положения
1. Теоретические сведения для выполнения практических работ №1 и №2.
2. Для корреляционной таблицы:
 * $$m_{x_i} = \sum_{j=1}^{k_y}m_{x_i y_j}$$ - частота появления варианты $$x_i$$
 * $$m_{y_j} = \sum_{i=1}^{k_x}m_{x_i y_j}$$ - частота появления варианты $y_j$
 * $$\sum_{i=1}^{k_x} m_{x_i} = \sum_{j=1}^{k_y} m_{y_j} = n$$
3. Статистическая оценка корреляционного момента:
 $$\mu_{xy} =\overline{xy} - \overline{x} - \overline{y}$$
4. Коэффициент корреляции: $$r = \frac{\mu_{xy}}{s_x s_y} $$
5. Преобразование Фишера: $$z=0.5 \ln(\frac{1+r}{1-r})$$
6. Стандартная ошибка среднего для преобразованного z: $$SE = \frac{1}{\sqrt{n-3}}$$
7. Формулы для определения границ доверительного интервала коэффициента корреляции:
 * $$z_u = z \mp z_{1- \alpha/2}*SE$$
 * $$z_{1- \alpha/2} = t(1- \gamma; df = \infty)$$ - табличные данные

## Постановка задачи
Из заданной генеральной совокупности сформировать выборку по второму признаку.
Провести статистическую обработку второй выборки в
объеме практических работ №1 и №2, с целью определения точечных
статистических оценок параметров распределения исследуемого признака
 (математического ожидания, дисперсии, среднеквадратичного отклонения, асимметрии и эксцесса). Для системы двух случайных величин
𝑋 (первый признак) и 𝑌 (второй признак) сформировать двумерную
выборку и найти статистическую оценку коэффициента корреляции,
построить доверительный интервал для коэффициента корреляции и
осуществить проверку статистической гипотезы о равенстве коэффициента
корреляции нулю. Полученные результаты содержательно проинтерпретировать.

## Порядок выполнения работы
1. Провести статистическую обработку второй выборки в объеме
практических работ №1 и №2, с целью определения точечных статистических оценок параметров распределения исследуемого признака
(математического ожидания, дисперсии, среднеквадратичного отклонения, асимметрии, эксцесса, моды, медианы и коэффициента
вариации)
2. Построить двумерный интервальный вариационный ряд, оформить
в виде таблицы.
3. По полученному двумерному интервальному вариационному ряду
построить корреляционную таблицу
4. Исходя из результатов корреляционной таблицы вычислить статистическую оценку корреляционного момента.
5. Вычислить коэффициент корреляции
6. Построить доверительный интервал для коэффициента корреляции при уровне значимости 𝛾 ∈ {0.95, 0.99}
7. Осуществить проверку статистической гипотезы о равенстве коэффициента корреляции нулю при заданном уровне значимости
𝛼 = 0.05

## Выполнение работы

Задание 1

In [1]:
import pandas as pd
import numpy as np


table = pd.read_csv("laptop_price.csv",delimiter=',')
table = table.drop(['Weight'], axis = 1)
table

Product  Price_euros
0     17-Y002nv (A10-9600P/6GB/2TB/Radeon       569.00
1                       IdeaPad 310-15ABR       499.00
2                                Aspire 5       579.00
3    17-ak002nv (A10-9620P/6GB/2TB/Radeon       655.01
4        X555QG-DM242T (A10-9620P/4GB/1TB       575.00
..                                    ...          ...
107                     IdeaPad 110-15IBR       329.00
108                        Aspire E5-774G       629.00
109                        Aspire ES1-572       361.80
110                         Inspiron 3567       428.00
111                         Inspiron 5567       499.00

[112 rows x 2 columns]

Ранжированный ряд

In [2]:
sortTable = table.sort_values('Price_euros')
sortTable

Product  Price_euros
48         C740-C9QX (3205U/2GB/32GB/Chrome       174.00
39                          Vivobook E200HA       191.90
44         V131 (X5-Z8350/4GB/32GB/FHD/W10)       196.00
33     E402WA-GA010T (E2-6110/2GB/32GB/W10)       199.00
50                     Chromebook C910-C2ST       199.00
..                                      ...          ...
3      17-ak002nv (A10-9620P/6GB/2TB/Radeon       655.01
36  FX550IK-DM018T (FX-9830P/8GB/1TB/Radeon       699.00
8                         IdeaPad 320-15ABR       899.00
35                       IdeaPad Y700-15ACZ       999.00
37                                Rog Strix      1695.00

[112 rows x 2 columns]

Вариационный ряд

In [3]:
sortTable['m_i'] = sortTable.groupby('Price_euros')['Price_euros'].transform('count')
sortTable= sortTable.drop_duplicates(subset=['Price_euros']).reset_index(drop = True)
sortTable['p*_i'] = sortTable['m_i']/sum(sortTable['m_i'])
sum_row = {'Product': 'ПРОВЕРКА','Price_euros':'', 'm_i': sum(sortTable['m_i']), 'p*_i': sum(sortTable['p*_i'])}
sortTable.append(sum_row, ignore_index=True)

Product Price_euros  m_i      p*_i
0          C740-C9QX (3205U/2GB/32GB/Chrome       174.0    1  0.008929
1                           Vivobook E200HA       191.9    1  0.008929
2          V131 (X5-Z8350/4GB/32GB/FHD/W10)       196.0    1  0.008929
3      E402WA-GA010T (E2-6110/2GB/32GB/W10)       199.0    2  0.017857
4                 K146 (N3350/4GB/32GB/W10)       202.9    1  0.008929
..                                      ...         ...  ...       ...
83  FX550IK-DM018T (FX-9830P/8GB/1TB/Radeon       699.0    1  0.008929
84                        IdeaPad 320-15ABR       899.0    1  0.008929
85                       IdeaPad Y700-15ACZ       999.0    1  0.008929
86                                Rog Strix      1695.0    1  0.008929
87                                 ПРОВЕРКА              112  1.000000

[88 rows x 4 columns]

Интервальный ряд

In [4]:
n = sortTable['Product'].size
print('n=',n)
k = 1 + 3.322*(np.log2(sortTable['Product'].size))//1
print('k=',k)
max_x = sortTable['Price_euros'].max()
min_x = sortTable['Price_euros'].min()
print('max_x=', max_x)
print('min_x=', min_x)
h = round((max_x - min_x)/k,3)
print('h=',h)
x0 = round(min_x - 1)
print('x0=',x0)
borders = []
for i in range(24):
    borders.append(x0+ i*h)
print(borders,'-границы промежутков')
size = 0
mi = []
for j in range(len(borders)-1):
    tmp = sortTable['Price_euros'].between(borders[j], borders[j+1], inclusive='right').tolist()
    for i in range(len(tmp)):
        if tmp[i]:
            size+=1
    mi.append(size)
    size = 0
print(mi, '- абсолютные частоты интервального ряда')
print(sum(mi), '- проверяем, что сумма не изменилась, значит частоты посчитаны верно')

intervals = []
for i in range(len(borders)-1):
    intervals.append([round(borders[i], 3), round(borders[i+1], 3)])

rangeTable = pd.DataFrame(data={'Промежуток': intervals, 'mi': mi})
print('\n')
rangeTable['pi'] = round(rangeTable['mi']/n,4)
print(rangeTable)
print('\nнайдем сумму относительных частот:')
print(round(sum(rangeTable['pi']),3),'- частоты посчитаны верно')
mid_intervals=[]
print('\n')
for i in range(len(borders)-1):
    mid_intervals.append(round((borders[i] + borders[i+1])/2, 3))
print(mid_intervals, ' - середины промежутков')
c = mid_intervals[len(mid_intervals) // 2]
df = pd.DataFrame({'xi': [], 'pi': [], 'ui': [], 'ui_pi': [], 'ui2_pi': [], 'ui3_pi': [], 'ui4_pi': []})
df['xi'] = mid_intervals
df['pi'] = rangeTable['pi']
df['ui'] = (df['xi'] - c)/ h
df['ui_pi'] = df['ui'] * df['pi']
df['ui2_pi'] = df['ui']**2 * df['pi']
df['ui3_pi'] = df['ui']**3 * df['pi']
df['ui4_pi'] = df['ui']**4 * df['pi']


x_mid_st = round(sum(df['xi'] * df['pi']), 3)
disp_st = round (sum(pow((df['xi'] - x_mid_st), 2) * df['pi']), 3)
print('мат ожидание: ', x_mid_st)
print('дисперсия ', disp_st)
sko_st = round(np.sqrt(disp_st), 3)
print('ско: ', sko_st)
print('медиана: ',  c)
print('мода: ', df['xi'][df['pi'].idxmax()] )


v = [sum(df['ui_pi'])]
for i in range(3):
    v.append(sum(df['ui'+ str(i+2) + '_pi']))

m = []
x_mid = v[0] * h + c
for j in range(4):
        m.append(sum(pow((df['xi'] - x_mid), j + 1) * df['pi']))
df_moment = pd.DataFrame({'v': v, 'm': m})
df_moment.round(3)
a_s = df_moment['m'][2] / pow(sko_st, 3)
e_k = df_moment['m'][3] / pow(sko_st, 4) - 3

df_as_ek = pd.DataFrame({'a_s': [a_s], 'e_k': [e_k]})

print('коэффициент ассиметрии a_s : ', round(df_as_ek['a_s'][0]), 3)
print('коэффициент эксцесса e_k : ', round(df_as_ek['e_k'][0], 3) )

print('\na_s > 0 => распределение скошено вправо, a_s > 0.5 => асимметрия существует')
print('e_k < 0 => наше распределение более высокое относительно нормального')



#из первой работы
intervals1 = []
for i in range(6):
    intervals1.append([0.495 + 0.5 * i, 0.495 + 0.5 * ( i + 1 )])

mi_1 = [2, 12, 11, 11, 5, 2]
pi_1 = [0.0465, 0.2791, 0.2558, 0.2558, 0.1163, 0.0465]

rangeTable1 = pd.DataFrame({'Промежуток': intervals1, 'mi': mi_1, 'pi': pi_1})
print('\nобработанныый интервальный ряд из первой работы:')
print(rangeTable1)

n= 87
k= 22.0
max_x= 1695.0
min_x= 174.0
h= 69.136
x0= 173
[173.0, 242.136, 311.272, 380.408, 449.544, 518.68, 587.816, 656.952, 726.088, 795.2239999999999, 864.3599999999999, 933.496, 1002.632, 1071.768, 1140.904, 1210.04, 1279.176, 1348.312, 1417.4479999999999, 1486.5839999999998, 1555.7199999999998, 1624.856, 1693.992, 1763.128] -границы промежутков
[10, 23, 18, 12, 8, 8, 4, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1] - абсолютные частоты интервального ряда
87 - проверяем, что сумма не изменилась, значит частоты посчитаны верно


              Промежуток  mi      pi
0       [173.0, 242.136]  10  0.1149
1     [242.136, 311.272]  23  0.2644
2     [311.272, 380.408]  18  0.2069
3     [380.408, 449.544]  12  0.1379
4      [449.544, 518.68]   8  0.0920
5      [518.68, 587.816]   8  0.0920
6     [587.816, 656.952]   4  0.0460
7     [656.952, 726.088]   1  0.0115
8     [726.088, 795.224]   0  0.0000
9      [795.224, 864.36]   0  0.0000
10     [864.36, 933.496]   1  0.0115
11   [933.496

Задание 2

In [5]:
table = pd.read_csv("laptop_price.csv",delimiter=',')


mas = np.empty((len(rangeTable),len(rangeTable1)))
mas.fill(0)

for k in range(len(table)):
    for i in range(len(rangeTable)):
        if rangeTable['Промежуток'][i][0] < table['Price_euros'][k] <= rangeTable['Промежуток'][i][1]:
            for j in range(len(rangeTable1)):
                if rangeTable1['Промежуток'][j][0] < table['Weight'][k] <= rangeTable1['Промежуток'][j][1]:
                    mas[i][j] += 1


print(mas)
print('\nПолучился двумерный интервальный вариационный ряд, строки которого'
      ' соответствуют интервалам параметра Price_euros, а столбцы Weight ')

[[ 1.  7.  2.  3.  0.  0.]
 [ 0. 16. 10.  4.  0.  0.]
 [ 1.  6.  3. 15.  1.  0.]
 [ 0.  3.  3.  8.  1.  0.]
 [ 0.  3.  4.  4.  0.  0.]
 [ 0.  0.  2.  4.  2.  0.]
 [ 0.  0.  1.  2.  1.  1.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.]]

Получился двумерный интервальный вариационный ряд, строки которого соответствуют интервалам параметра Price_euros, а столбцы Weight 


Задание 3

In [6]:
cor_tab = pd.DataFrame(mas, columns=['y1', 'y2','y3','y4','y5','y6',])
cor_tab['m_xi'] = cor_tab.sum(axis=1)
m_xi = sum(cor_tab['m_xi'])
cor_tab = cor_tab.append(cor_tab.sum(axis=0), ignore_index=True)
m_yi = 0
for i in range(len(cor_tab.columns)-1):
    m_yi += cor_tab['y' + str(i+1)][len(cor_tab)-1]
print(cor_tab)

print('\n частота появления варианты x_i при заданном y: m_xi = ', m_xi)
print('частота появления варианты y_i при заданном x: m_yi = ', m_yi)
print('частоты совпали и равны n = 112, значит таблица построена верно')



     y1    y2    y3    y4   y5   y6   m_xi
0   1.0   7.0   2.0   3.0  0.0  0.0   13.0
1   0.0  16.0  10.0   4.0  0.0  0.0   30.0
2   1.0   6.0   3.0  15.0  1.0  0.0   26.0
3   0.0   3.0   3.0   8.0  1.0  0.0   15.0
4   0.0   3.0   4.0   4.0  0.0  0.0   11.0
5   0.0   0.0   2.0   4.0  2.0  0.0    8.0
6   0.0   0.0   1.0   2.0  1.0  1.0    5.0
7   0.0   0.0   0.0   1.0  0.0  0.0    1.0
8   0.0   0.0   0.0   0.0  0.0  0.0    0.0
9   0.0   0.0   0.0   0.0  0.0  0.0    0.0
10  0.0   0.0   0.0   1.0  0.0  0.0    1.0
11  0.0   0.0   0.0   0.0  1.0  0.0    1.0
12  0.0   0.0   0.0   0.0  0.0  0.0    0.0
13  0.0   0.0   0.0   0.0  0.0  0.0    0.0
14  0.0   0.0   0.0   0.0  0.0  0.0    0.0
15  0.0   0.0   0.0   0.0  0.0  0.0    0.0
16  0.0   0.0   0.0   0.0  0.0  0.0    0.0
17  0.0   0.0   0.0   0.0  0.0  0.0    0.0
18  0.0   0.0   0.0   0.0  0.0  0.0    0.0
19  0.0   0.0   0.0   0.0  0.0  0.0    0.0
20  0.0   0.0   0.0   0.0  0.0  0.0    0.0
21  0.0   0.0   0.0   0.0  0.0  0.0    0.0
22  0.0   0

Задание 4, 5

In [11]:
mid_intervals1 = []
for i in range(6):
    mid_intervals1.append((intervals1[i][0] + intervals1[i][1])/2)

x_mid = 0
y_mid = 0
x_disp = 0
y_disp = 0
for i in range(6):
   y_mid += mid_intervals1[i] * cor_tab['y' + str(i + 1)][len(cor_tab) - 1]


for i in range(len(cor_tab) - 1):
    x_mid += mid_intervals[i] * cor_tab['m_xi'][i]

x_mid/= 112
y_mid/= 112
x_sko = np.sqrt(df_moment['m'][1])
y_disp = 0.385 #из второй работы
y_sko = np.sqrt(y_disp)
print('выборочное среднее для x: ', round(x_mid, 3))
print('выборочное среднее для y: ', round(y_mid, 3))
print('выборочная дисперсия для x: ', round(df_moment['m'][1], 3))
print('выборочная дисперсия для y: ', y_disp)
print('выборочное ско x: ', round(x_sko, 3))
print('выборочное ско y: ', round(y_sko, 3))

выборочное среднее для x:  387.198
выборочное среднее для y:  1.839
выборочная дисперсия для x:  41846.943
выборочная дисперсия для y:  0.385
выборочное ско x:  204.565
выборочное ско y:  0.62


In [8]:
print('способ через условные варианты:')

print('условные варианты для второго параметра:')
cond_var2 = df['ui'].round(3).tolist()
print(cond_var2)
print('условные варианты для первого параметра(из второй работы):')
cond_var1 = [-3.0, -2, -1, 0, 1, 2]
print(cond_var1)
cond_var1_mid = np.mean(cond_var1)
cond_var2_mid = np.mean(cond_var2)
sum = 0
for i in range(len(cond_var2)):
    for j in range(len(cond_var1)):
        sum+= mas[i][j] * cond_var1[j]*cond_var2[i]
sum/=112
mu = sum- cond_var1_mid* cond_var2_mid
print('статистическая оценка корреляционного момента: ', round(mu, 3))
corr = ( sum - cond_var1_mid* cond_var2_mid)/ (x_sko * y_sko)
print('коэффициент корреляции: ', round(corr, 3))
print('значение коэффициента корреляции близко к 0 => связь между x и y очень слабая')

способ через условные варианты:
условные варианты для второго параметра:
[-11.0, -10.0, -9.0, -8.0, -7.0, -6.0, -5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0]
условные варианты для первого параметра(из второй работы):
[-3.0, -2, -1, 0, 1, 2]
статистическая оценка корреляционного момента:  8.286
коэффициент корреляции:  0.065
значение коэффициента корреляции близко к 0 => связь между x и y очень слабая


Задание 6

In [9]:
import math

z = 0.5 * math.log((1 + corr)/ (1 - corr))
print('по преобразованию Фишера z = ', round(z, 3))
se = 1/ (112 - 3)
print('стандартная ошибка среднего SE = ', round(se, 3))
print('g = 0.95 => a = 1 - g = 0.05 => по таблице t =~ 1.96')
t = 1.96
print('доверительный интервал для g = 0.95: ', (round((np.exp(2*(z - t * se)) - 1)/ (np.exp(2*(z - t * se)) + 1), 3), round((np.exp(2*(z + t * se)) - 1)/ (np.exp(2*(z + t * se)) + 1), 3)))

print('g = 0.99 => a = 1 - g = 0.01 => по таблице t =~ 2.5758')
t = 2.5758
print('доверительный интервал для g = 0.99: ', (round((np.exp(2*(z - t * se)) - 1)/ (np.exp(2*(z - t * se)) + 1), 3), round((np.exp(2*(z + t * se)) - 1)/ (np.exp(2*(z + t * se)) + 1), 3)) )

по преобразованию Фишера z =  0.065
стандартная ошибка среднего SE =  0.009
g = 0.95 => a = 1 - g = 0.05 => по таблице t =~ 1.96
доверительный интервал для g = 0.95:  (0.047, 0.083)
g = 0.99 => a = 1 - g = 0.01 => по таблице t =~ 2.5758
доверительный интервал для g = 0.99:  (0.042, 0.089)


Задание 7

In [10]:
a = 0.05
n = 112
print('a = ', a)
print('H_0: r = 0')
print('H_1: r != 0')
print('t_крит при a = 0.05 и n - 2 = 110 примерно равно  ',  1.98)
print('T_набл = ', round(corr * np.sqrt(n - 2) / np.sqrt(1 - corr**2), 3))
print('|T_набл| < t_крит => гипотезу H_0 не отклоняем => отсутствует линейная завсисимость')




a =  0.05
H_0: r = 0
H_1: r != 0
t_крит при a = 0.05 и n - 2 = 110 примерно равно   1.98
T_набл =  0.686
|T_набл| < t_крит => гипотезу H_0 не отклоняем => отсутствует линейная завсисимость


## Выводы
В процессе выполнения практической работы была обработана вторая выборка в объеме практических работ №1 и №2(найдены мат.ожидание, дисперсия, среднеквадратичное отклонение, коэффициенты асимметрии и эксцесса)
По исходной системе случайных величин была сформирована двумерная выборка и построена корреляционная таблица, с помощью которой был найден коэффициент корреляции. В результате анализа коэффициента корреляции выяснилось, что
в системе случайных величин отсутствует линейная зависимость.